### PR TITLE
Filter by incident type

### PR DESCRIPTION
**Pull request by emilasuska**
added button and menu to filter by incident type

### CODE REVIEW

**Review by tabernik — APPROVED** [review]
looks good!

**Review by renakollmannsuhr — COMMENTED** [review]
This works great! Could we possibly change the icon to something like this instead?
Screenshot 2024-11-18 at 16 43 52

I think this more clearly conveys filters?

**Review by renakollmannsuhr — COMMENTED** [review]
Also just from a progress standpoint, are we going to filter by time as well? And what would we filter by?

**Comment by emilasuska** [comment]
> Also just from a progress standpoint, are we still going to filter by time as well? And what times would we filter by?

I thought the fading markers would make it so we don't really need to filter by time, but if we want to filter by time I can look into  doing it.

**Pull request merged**
